package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Choujiang;
import org.linlinjava.litemall.db.domain.example.ChoujiangExample;

public interface ChoujiangMapper {
    long countByExample(ChoujiangExample example);

    int deleteByExample(ChoujiangExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Choujiang record);

    int insertSelective(Choujiang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choujiang
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Choujiang selectOneByExample(ChoujiangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choujiang
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Choujiang selectOneByExampleSelective(@Param("example") ChoujiangExample example, @Param("selective") Choujiang.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choujiang
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Choujiang> selectByExampleSelective(@Param("example") ChoujiangExample example, @Param("selective") Choujiang.Column ... selective);

    List<Choujiang> selectByExample(ChoujiangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choujiang
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Choujiang selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Choujiang.Column ... selective);

    Choujiang selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choujiang
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Choujiang selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Choujiang record, @Param("example") ChoujiangExample example);

    int updateByExample(@Param("record") Choujiang record, @Param("example") ChoujiangExample example);

    int updateByPrimaryKeySelective(Choujiang record);

    int updateByPrimaryKey(Choujiang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choujiang
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ChoujiangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choujiang
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}