package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.DaySignPrize;
import org.linlinjava.litemall.db.domain.example.DaySignPrizeExample;

public interface DaySignPrizeMapper {
    long countByExample(DaySignPrizeExample example);

    int deleteByExample(DaySignPrizeExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(DaySignPrize record);

    int insertSelective(DaySignPrize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_sign_prize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaySignPrize selectOneByExample(DaySignPrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_sign_prize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaySignPrize selectOneByExampleSelective(@Param("example") DaySignPrizeExample example, @Param("selective") DaySignPrize.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_sign_prize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DaySignPrize> selectByExampleSelective(@Param("example") DaySignPrizeExample example, @Param("selective") DaySignPrize.Column ... selective);

    List<DaySignPrize> selectByExample(DaySignPrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_sign_prize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaySignPrize selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DaySignPrize.Column ... selective);

    DaySignPrize selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_sign_prize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DaySignPrize selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") DaySignPrize record, @Param("example") DaySignPrizeExample example);

    int updateByExample(@Param("record") DaySignPrize record, @Param("example") DaySignPrizeExample example);

    int updateByPrimaryKeySelective(DaySignPrize record);

    int updateByPrimaryKey(DaySignPrize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_sign_prize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DaySignPrizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_sign_prize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}