package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ExperienceTreasure;
import org.linlinjava.litemall.db.domain.example.ExperienceTreasureExample;

public interface ExperienceTreasureMapper {
    long countByExample(ExperienceTreasureExample example);

    int deleteByExample(ExperienceTreasureExample example);

    int deleteByPrimaryKey(Integer attrib);

    int insert(ExperienceTreasure record);

    int insertSelective(ExperienceTreasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_treasure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ExperienceTreasure selectOneByExample(ExperienceTreasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_treasure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ExperienceTreasure selectOneByExampleSelective(@Param("example") ExperienceTreasureExample example, @Param("selective") ExperienceTreasure.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_treasure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ExperienceTreasure> selectByExampleSelective(@Param("example") ExperienceTreasureExample example, @Param("selective") ExperienceTreasure.Column ... selective);

    List<ExperienceTreasure> selectByExample(ExperienceTreasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_treasure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ExperienceTreasure selectByPrimaryKeySelective(@Param("attrib") Integer attrib, @Param("selective") ExperienceTreasure.Column ... selective);

    ExperienceTreasure selectByPrimaryKey(Integer attrib);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_treasure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ExperienceTreasure selectByPrimaryKeyWithLogicalDelete(@Param("attrib") Integer attrib, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") ExperienceTreasure record, @Param("example") ExperienceTreasureExample example);

    int updateByExample(@Param("record") ExperienceTreasure record, @Param("example") ExperienceTreasureExample example);

    int updateByPrimaryKeySelective(ExperienceTreasure record);

    int updateByPrimaryKey(ExperienceTreasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_treasure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ExperienceTreasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience_treasure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer attrib);
}