package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Map;
import org.linlinjava.litemall.db.domain.example.MapExample;

public interface MapMapper {
    long countByExample(MapExample example);

    int deleteByExample(MapExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Map record);

    int insertSelective(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Map selectOneByExample(MapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Map selectOneByExampleSelective(@Param("example") MapExample example, @Param("selective") Map.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Map> selectByExampleSelective(@Param("example") MapExample example, @Param("selective") Map.Column ... selective);

    List<Map> selectByExample(MapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Map selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Map.Column ... selective);

    Map selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Map selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Map record, @Param("example") MapExample example);

    int updateByExample(@Param("record") Map record, @Param("example") MapExample example);

    int updateByPrimaryKeySelective(Map record);

    int updateByPrimaryKey(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}