package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.NpcDialogueFrame;
import org.linlinjava.litemall.db.domain.example.NpcDialogueFrameExample;

public interface NpcDialogueFrameMapper {
    long countByExample(NpcDialogueFrameExample example);

    int deleteByExample(NpcDialogueFrameExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(NpcDialogueFrame record);

    int insertSelective(NpcDialogueFrame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue_frame
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NpcDialogueFrame selectOneByExample(NpcDialogueFrameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue_frame
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NpcDialogueFrame selectOneByExampleSelective(@Param("example") NpcDialogueFrameExample example, @Param("selective") NpcDialogueFrame.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue_frame
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<NpcDialogueFrame> selectByExampleSelective(@Param("example") NpcDialogueFrameExample example, @Param("selective") NpcDialogueFrame.Column ... selective);

    List<NpcDialogueFrame> selectByExample(NpcDialogueFrameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue_frame
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NpcDialogueFrame selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") NpcDialogueFrame.Column ... selective);

    NpcDialogueFrame selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue_frame
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NpcDialogueFrame selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") NpcDialogueFrame record, @Param("example") NpcDialogueFrameExample example);

    int updateByExample(@Param("record") NpcDialogueFrame record, @Param("example") NpcDialogueFrameExample example);

    int updateByPrimaryKeySelective(NpcDialogueFrame record);

    int updateByPrimaryKey(NpcDialogueFrame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue_frame
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") NpcDialogueFrameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue_frame
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}