package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.NpcDialogue;
import org.linlinjava.litemall.db.domain.example.NpcDialogueExample;

public interface NpcDialogueMapper {
    long countByExample(NpcDialogueExample example);

    int deleteByExample(NpcDialogueExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(NpcDialogue record);

    int insertSelective(NpcDialogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NpcDialogue selectOneByExample(NpcDialogueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NpcDialogue selectOneByExampleSelective(@Param("example") NpcDialogueExample example, @Param("selective") NpcDialogue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<NpcDialogue> selectByExampleSelective(@Param("example") NpcDialogueExample example, @Param("selective") NpcDialogue.Column ... selective);

    List<NpcDialogue> selectByExample(NpcDialogueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NpcDialogue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") NpcDialogue.Column ... selective);

    NpcDialogue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NpcDialogue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") NpcDialogue record, @Param("example") NpcDialogueExample example);

    int updateByExample(@Param("record") NpcDialogue record, @Param("example") NpcDialogueExample example);

    int updateByPrimaryKeySelective(NpcDialogue record);

    int updateByPrimaryKey(NpcDialogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") NpcDialogueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table npc_dialogue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}