package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.PackModification;
import org.linlinjava.litemall.db.domain.example.PackModificationExample;

public interface PackModificationMapper {
    long countByExample(PackModificationExample example);

    int deleteByExample(PackModificationExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PackModification record);

    int insertSelective(PackModification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_modification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PackModification selectOneByExample(PackModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_modification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PackModification selectOneByExampleSelective(@Param("example") PackModificationExample example, @Param("selective") PackModification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_modification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<PackModification> selectByExampleSelective(@Param("example") PackModificationExample example, @Param("selective") PackModification.Column ... selective);

    List<PackModification> selectByExample(PackModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_modification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PackModification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") PackModification.Column ... selective);

    PackModification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_modification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PackModification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") PackModification record, @Param("example") PackModificationExample example);

    int updateByExample(@Param("record") PackModification record, @Param("example") PackModificationExample example);

    int updateByPrimaryKeySelective(PackModification record);

    int updateByPrimaryKey(PackModification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_modification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PackModificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pack_modification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}