package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.PetHelpType;
import org.linlinjava.litemall.db.domain.example.PetHelpTypeExample;

public interface PetHelpTypeMapper {
    long countByExample(PetHelpTypeExample example);

    int deleteByExample(PetHelpTypeExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PetHelpType record);

    int insertSelective(PetHelpType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_help_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PetHelpType selectOneByExample(PetHelpTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_help_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PetHelpType selectOneByExampleSelective(@Param("example") PetHelpTypeExample example, @Param("selective") PetHelpType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_help_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<PetHelpType> selectByExampleSelective(@Param("example") PetHelpTypeExample example, @Param("selective") PetHelpType.Column ... selective);

    List<PetHelpType> selectByExample(PetHelpTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_help_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PetHelpType selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") PetHelpType.Column ... selective);

    PetHelpType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_help_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PetHelpType selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") PetHelpType record, @Param("example") PetHelpTypeExample example);

    int updateByExample(@Param("record") PetHelpType record, @Param("example") PetHelpTypeExample example);

    int updateByPrimaryKeySelective(PetHelpType record);

    int updateByPrimaryKey(PetHelpType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_help_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PetHelpTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_help_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}