package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Pets;
import org.linlinjava.litemall.db.domain.example.PetsExample;

public interface PetsMapper {
    long countByExample(PetsExample example);

    int deleteByExample(PetsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Pets record);

    int insertSelective(Pets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Pets selectOneByExample(PetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Pets selectOneByExampleSelective(@Param("example") PetsExample example, @Param("selective") Pets.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Pets> selectByExampleSelective(@Param("example") PetsExample example, @Param("selective") Pets.Column ... selective);

    List<Pets> selectByExample(PetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Pets selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Pets.Column ... selective);

    Pets selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Pets selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Pets record, @Param("example") PetsExample example);

    int updateByExample(@Param("record") Pets record, @Param("example") PetsExample example);

    int updateByPrimaryKeySelective(Pets record);

    int updateByPrimaryKey(Pets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pets
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}