package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.RenwuMonster;
import org.linlinjava.litemall.db.domain.example.RenwuMonsterExample;

public interface RenwuMonsterMapper {
    long countByExample(RenwuMonsterExample example);

    int deleteByExample(RenwuMonsterExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(RenwuMonster record);

    int insertSelective(RenwuMonster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renwu_monster
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RenwuMonster selectOneByExample(RenwuMonsterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renwu_monster
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RenwuMonster selectOneByExampleSelective(@Param("example") RenwuMonsterExample example, @Param("selective") RenwuMonster.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renwu_monster
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<RenwuMonster> selectByExampleSelective(@Param("example") RenwuMonsterExample example, @Param("selective") RenwuMonster.Column ... selective);

    List<RenwuMonster> selectByExample(RenwuMonsterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renwu_monster
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RenwuMonster selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") RenwuMonster.Column ... selective);

    RenwuMonster selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renwu_monster
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RenwuMonster selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") RenwuMonster record, @Param("example") RenwuMonsterExample example);

    int updateByExample(@Param("record") RenwuMonster record, @Param("example") RenwuMonsterExample example);

    int updateByPrimaryKeySelective(RenwuMonster record);

    int updateByPrimaryKey(RenwuMonster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renwu_monster
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") RenwuMonsterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table renwu_monster
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}