package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Reports;
import org.linlinjava.litemall.db.domain.example.ReportsExample;

public interface ReportsMapper {
    long countByExample(ReportsExample example);

    int deleteByExample(ReportsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Reports record);

    int insertSelective(Reports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Reports selectOneByExample(ReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Reports selectOneByExampleSelective(@Param("example") ReportsExample example, @Param("selective") Reports.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Reports> selectByExampleSelective(@Param("example") ReportsExample example, @Param("selective") Reports.Column ... selective);

    List<Reports> selectByExample(ReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Reports selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Reports.Column ... selective);

    Reports selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Reports selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Reports record, @Param("example") ReportsExample example);

    int updateByExample(@Param("record") Reports record, @Param("example") ReportsExample example);

    int updateByPrimaryKeySelective(Reports record);

    int updateByPrimaryKey(Reports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ReportsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reports
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}