package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SaleClassifyGood;
import org.linlinjava.litemall.db.domain.example.SaleClassifyGoodExample;

public interface SaleClassifyGoodMapper {
    long countByExample(SaleClassifyGoodExample example);

    int deleteByExample(SaleClassifyGoodExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SaleClassifyGood record);

    int insertSelective(SaleClassifyGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_classify_good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SaleClassifyGood selectOneByExample(SaleClassifyGoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_classify_good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SaleClassifyGood selectOneByExampleSelective(@Param("example") SaleClassifyGoodExample example, @Param("selective") SaleClassifyGood.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_classify_good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SaleClassifyGood> selectByExampleSelective(@Param("example") SaleClassifyGoodExample example, @Param("selective") SaleClassifyGood.Column ... selective);

    List<SaleClassifyGood> selectByExample(SaleClassifyGoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_classify_good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SaleClassifyGood selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SaleClassifyGood.Column ... selective);

    SaleClassifyGood selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_classify_good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SaleClassifyGood selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") SaleClassifyGood record, @Param("example") SaleClassifyGoodExample example);

    int updateByExample(@Param("record") SaleClassifyGood record, @Param("example") SaleClassifyGoodExample example);

    int updateByPrimaryKeySelective(SaleClassifyGood record);

    int updateByPrimaryKey(SaleClassifyGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_classify_good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SaleClassifyGoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_classify_good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}