package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ShowTasks;
import org.linlinjava.litemall.db.domain.example.ShowTasksExample;

public interface ShowTasksMapper {
    long countByExample(ShowTasksExample example);

    int deleteByExample(ShowTasksExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ShowTasks record);

    int insertSelective(ShowTasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_tasks
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShowTasks selectOneByExample(ShowTasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_tasks
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShowTasks selectOneByExampleSelective(@Param("example") ShowTasksExample example, @Param("selective") ShowTasks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_tasks
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShowTasks> selectByExampleSelective(@Param("example") ShowTasksExample example, @Param("selective") ShowTasks.Column ... selective);

    List<ShowTasks> selectByExample(ShowTasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_tasks
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShowTasks selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShowTasks.Column ... selective);

    ShowTasks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_tasks
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShowTasks selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") ShowTasks record, @Param("example") ShowTasksExample example);

    int updateByExample(@Param("record") ShowTasks record, @Param("example") ShowTasksExample example);

    int updateByPrimaryKeySelective(ShowTasks record);

    int updateByPrimaryKey(ShowTasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_tasks
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShowTasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_tasks
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}