package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Shuxingduiying;
import org.linlinjava.litemall.db.domain.example.ShuxingduiyingExample;

public interface ShuxingduiyingMapper {
    long countByExample(ShuxingduiyingExample example);

    int deleteByExample(ShuxingduiyingExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Shuxingduiying record);

    int insertSelective(Shuxingduiying record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxingduiying
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Shuxingduiying selectOneByExample(ShuxingduiyingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxingduiying
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Shuxingduiying selectOneByExampleSelective(@Param("example") ShuxingduiyingExample example, @Param("selective") Shuxingduiying.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxingduiying
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Shuxingduiying> selectByExampleSelective(@Param("example") ShuxingduiyingExample example, @Param("selective") Shuxingduiying.Column ... selective);

    List<Shuxingduiying> selectByExample(ShuxingduiyingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxingduiying
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Shuxingduiying selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Shuxingduiying.Column ... selective);

    Shuxingduiying selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxingduiying
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Shuxingduiying selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Shuxingduiying record, @Param("example") ShuxingduiyingExample example);

    int updateByExample(@Param("record") Shuxingduiying record, @Param("example") ShuxingduiyingExample example);

    int updateByPrimaryKeySelective(Shuxingduiying record);

    int updateByPrimaryKey(Shuxingduiying record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxingduiying
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShuxingduiyingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxingduiying
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}