package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Skilldata;
import org.linlinjava.litemall.db.domain.example.SkilldataExample;

public interface SkilldataMapper {
    long countByExample(SkilldataExample example);

    int deleteByExample(SkilldataExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Skilldata record);

    int insertSelective(Skilldata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilldata
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skilldata selectOneByExample(SkilldataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilldata
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skilldata selectOneByExampleSelective(@Param("example") SkilldataExample example, @Param("selective") Skilldata.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilldata
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Skilldata> selectByExampleSelective(@Param("example") SkilldataExample example, @Param("selective") Skilldata.Column ... selective);

    List<Skilldata> selectByExample(SkilldataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilldata
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skilldata selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Skilldata.Column ... selective);

    Skilldata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilldata
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skilldata selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Skilldata record, @Param("example") SkilldataExample example);

    int updateByExample(@Param("record") Skilldata record, @Param("example") SkilldataExample example);

    int updateByPrimaryKeySelective(Skilldata record);

    int updateByPrimaryKey(Skilldata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilldata
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SkilldataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilldata
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}