package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Skilljineng;
import org.linlinjava.litemall.db.domain.example.SkilljinengExample;

public interface SkilljinengMapper {
    long countByExample(SkilljinengExample example);

    int deleteByExample(SkilljinengExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Skilljineng record);

    int insertSelective(Skilljineng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilljineng
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skilljineng selectOneByExample(SkilljinengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilljineng
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skilljineng selectOneByExampleSelective(@Param("example") SkilljinengExample example, @Param("selective") Skilljineng.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilljineng
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Skilljineng> selectByExampleSelective(@Param("example") SkilljinengExample example, @Param("selective") Skilljineng.Column ... selective);

    List<Skilljineng> selectByExample(SkilljinengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilljineng
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skilljineng selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Skilljineng.Column ... selective);

    Skilljineng selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilljineng
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skilljineng selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Skilljineng record, @Param("example") SkilljinengExample example);

    int updateByExample(@Param("record") Skilljineng record, @Param("example") SkilljinengExample example);

    int updateByPrimaryKeySelective(Skilljineng record);

    int updateByPrimaryKey(Skilljineng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilljineng
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SkilljinengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skilljineng
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}