package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Skills;
import org.linlinjava.litemall.db.domain.example.SkillsExample;

public interface SkillsMapper {
    long countByExample(SkillsExample example);

    int deleteByExample(SkillsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Skills record);

    int insertSelective(Skills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skills selectOneByExample(SkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skills selectOneByExampleSelective(@Param("example") SkillsExample example, @Param("selective") Skills.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Skills> selectByExampleSelective(@Param("example") SkillsExample example, @Param("selective") Skills.Column ... selective);

    List<Skills> selectByExample(SkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skills selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Skills.Column ... selective);

    Skills selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Skills selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Skills record, @Param("example") SkillsExample example);

    int updateByExample(@Param("record") Skills record, @Param("example") SkillsExample example);

    int updateByPrimaryKeySelective(Skills record);

    int updateByPrimaryKey(Skills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}