package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Srenwu;
import org.linlinjava.litemall.db.domain.example.SrenwuExample;

public interface SrenwuMapper {
    long countByExample(SrenwuExample example);

    int deleteByExample(SrenwuExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Srenwu record);

    int insertSelective(Srenwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srenwu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Srenwu selectOneByExample(SrenwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srenwu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Srenwu selectOneByExampleSelective(@Param("example") SrenwuExample example, @Param("selective") Srenwu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srenwu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Srenwu> selectByExampleSelective(@Param("example") SrenwuExample example, @Param("selective") Srenwu.Column ... selective);

    List<Srenwu> selectByExample(SrenwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srenwu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Srenwu selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Srenwu.Column ... selective);

    Srenwu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srenwu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Srenwu selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") Srenwu record, @Param("example") SrenwuExample example);

    int updateByExample(@Param("record") Srenwu record, @Param("example") SrenwuExample example);

    int updateByPrimaryKeySelective(Srenwu record);

    int updateByPrimaryKey(Srenwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srenwu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SrenwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srenwu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}