package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.StoreInfo;
import org.linlinjava.litemall.db.domain.example.StoreInfoExample;

public interface StoreInfoMapper {
    long countByExample(StoreInfoExample example);

    int deleteByExample(StoreInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(StoreInfo record);

    int insertSelective(StoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StoreInfo selectOneByExample(StoreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StoreInfo selectOneByExampleSelective(@Param("example") StoreInfoExample example, @Param("selective") StoreInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<StoreInfo> selectByExampleSelective(@Param("example") StoreInfoExample example, @Param("selective") StoreInfo.Column ... selective);

    List<StoreInfo> selectByExample(StoreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StoreInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") StoreInfo.Column ... selective);

    StoreInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StoreInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") StoreInfo record, @Param("example") StoreInfoExample example);

    int updateByExample(@Param("record") StoreInfo record, @Param("example") StoreInfoExample example);

    int updateByPrimaryKeySelective(StoreInfo record);

    int updateByPrimaryKey(StoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") StoreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}