package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.StoreGoods;
import org.linlinjava.litemall.db.domain.example.StoreGoodsExample;

public interface StoreGoodsMapper {
    long countByExample(StoreGoodsExample example);

    int deleteByExample(StoreGoodsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(StoreGoods record);

    int insertSelective(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StoreGoods selectOneByExample(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StoreGoods selectOneByExampleSelective(@Param("example") StoreGoodsExample example, @Param("selective") StoreGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<StoreGoods> selectByExampleSelective(@Param("example") StoreGoodsExample example, @Param("selective") StoreGoods.Column ... selective);

    List<StoreGoods> selectByExample(StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StoreGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") StoreGoods.Column ... selective);

    StoreGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StoreGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") StoreGoods record, @Param("example") StoreGoodsExample example);

    int updateByExample(@Param("record") StoreGoods record, @Param("example") StoreGoodsExample example);

    int updateByPrimaryKeySelective(StoreGoods record);

    int updateByPrimaryKey(StoreGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") StoreGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}