package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZhuangbeiInfo;
import org.linlinjava.litemall.db.domain.example.ZhuangbeiInfoExample;

public interface ZhuangbeiInfoMapper {
    long countByExample(ZhuangbeiInfoExample example);

    int deleteByExample(ZhuangbeiInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ZhuangbeiInfo record);

    int insertSelective(ZhuangbeiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhuangbei_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZhuangbeiInfo selectOneByExample(ZhuangbeiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhuangbei_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZhuangbeiInfo selectOneByExampleSelective(@Param("example") ZhuangbeiInfoExample example, @Param("selective") ZhuangbeiInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhuangbei_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZhuangbeiInfo> selectByExampleSelective(@Param("example") ZhuangbeiInfoExample example, @Param("selective") ZhuangbeiInfo.Column ... selective);

    List<ZhuangbeiInfo> selectByExample(ZhuangbeiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhuangbei_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZhuangbeiInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZhuangbeiInfo.Column ... selective);

    ZhuangbeiInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhuangbei_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZhuangbeiInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") ZhuangbeiInfo record, @Param("example") ZhuangbeiInfoExample example);

    int updateByExample(@Param("record") ZhuangbeiInfo record, @Param("example") ZhuangbeiInfoExample example);

    int updateByPrimaryKeySelective(ZhuangbeiInfo record);

    int updateByPrimaryKey(ZhuangbeiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhuangbei_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ZhuangbeiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhuangbei_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}